config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :sauna_tags
  resources :sauna_rooms
  resources :sauna_amenities
  resources :sauna_roles
  resources :reviews
  resources :activities
  resources :saunas do
    get :search , on: :collection
    get :incremental_search , on: :collection
    get :recommend , on: :collection
  end
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
   }
  resources :users
  root 'users#index'

  get 'search', to: 'saunas#search'
  get 'incremental_search', to: 'saunas#incremental_search'

  resources :wents, only: [:create, :show, :destroy]
  resources :likes, only: [:create, :show, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

   # token auth routes available at /api/v1/auth
  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        registrations: 'api/auth/registrations',
        sessions: 'api/auth/sessions',
        passwords: 'api/auth/passwords',
    }
 end

 mount Sidekiq::Web, at: '/sidekiq'
 Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  [user, password] == ["kawayuta","mirainoyuuta2116"]
end 
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :sauna
    belongs_to :user
    belongs_to :review
    has_many :likes
    accepts_nested_attributes_for :review, :allow_destroy => true

    mount_uploaders :images, ActivityImageUploader
    
    def created_at
        attributes['created_at'].strftime("%Y/%m/%d")
      end
      
    def parsed_tags(images)
        return JSON.parse(images) if images.present?
        {}
    end

    def self.decode_base64_image(encoded_file)
        decoded_file = Base64.decode64(encoded_file)
        file = Tempfile.new(['image','.jpg'])
        file.binmode
        file.write decoded_file
        
        return file
    end
end

app/controllers/activities_controller.rb
require 'json'
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]
  protect_from_forgery
  # before_action :authenticate_user!

  # GET /activities or /activities.json
  def index
    @activities = Activity.all.order(id: :DESC).page(params[:page]).per(10)
  end

  # GET /activities/1 or /activities/1.json
  def show 
    # render json: { activities: current_user.activities.find_by(sauna_id: params[:id])}
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create

    if activity_params[:images].present?
      imgArray = []
      activity_params[:images].each do |d|
        imgArray.append(Activity.decode_base64_image(d))
      end
      attrs = activity_params
      attrs[:images] = imgArray
      @activity = Activity.new(attrs)

      begin
        respond_to do |format|
          if @activity.save && imgArray && @activity.save(images: imgArray)
            format.html { redirect_to @activity, notice: "Activity was successfully created." }
            format.json { render :show, status: :created, location: @activity }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @activity.errors, status: :unprocessable_entity }
          end
        end
      ensure
        imgArray.each do |d|
          d.close
          d.unlink
        end
      end
      
    else
      @activity = Activity.new(activity_params)
      respond_to do |format|
        if @activity.save
          format.html { redirect_to @activity, notice: "Activity was successfully created." }
          format.json { render :show, status: :created, location: @activity }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @activity.errors, status: :unprocessable_entity }
        end
      end
    end




  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    
    def activity_params
      params.permit(:sauna_id, :user_id, :body, :image, :sauna_time, :sauna_count, :mizuburo_time, :mizuburo_count, :rest_time, :rest_count, images: [], review_attributes: [:id, :sauna_id, :user_id, :cleanliness, :customer_service, :equipment, :customer_manner, :cost_performance])
    end


end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :sauna_time %>
    <%= form.number_field :sauna_time %>
  </div>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count %>
  </div>

  <div class="field">
    <%= form.label :mizuburo_time %>
    <%= form.number_field :mizuburo_time %>
  </div>

  <div class="field">
    <%= form.label :mizuburo_count %>
    <%= form.number_field :mizuburo_count %>
  </div>

  <div class="field">
    <%= form.label :rest_time %>
    <%= form.number_field :rest_time %>
  </div>

  <div class="field">
    <%= form.label :rest_time %>
    <%= form.text_field :rest_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Image</th>
      <th>Sauna time</th>
      <th>Count</th>
      <th>Mizuburo time</th>
      <th>Mizuburo count</th>
      <th>Rest time</th>
      <th>Rest time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.body %></td>
        <td><%= activity.image %></td>
        <td><%= activity.sauna_time %></td>
        <td><%= activity.count %></td>
        <td><%= activity.mizuburo_time %></td>
        <td><%= activity.mizuburo_count %></td>
        <td><%= activity.rest_time %></td>
        <td><%= activity.rest_time %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @activity.body %>
</p>

<p>
  <strong>Image:</strong>
  <%= @activity.image %>
</p>

<p>
  <strong>Sauna time:</strong>
  <%= @activity.sauna_time %>
</p>

<p>
  <strong>Count:</strong>
  <%= @activity.count %>
</p>

<p>
  <strong>Mizuburo time:</strong>
  <%= @activity.mizuburo_time %>
</p>

<p>
  <strong>Mizuburo count:</strong>
  <%= @activity.mizuburo_count %>
</p>

<p>
  <strong>Rest time:</strong>
  <%= @activity.rest_time %>
</p>

<p>
  <strong>Rest time:</strong>
  <%= @activity.rest_time %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>